//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.16 at 12:02:59 PM CEST 
//


package de.uniluebeck.itm.osm2sumo.elements;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for connectionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="connectionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="connection" type="{}connectionType"/>
 *         &lt;element name="prohibition" type="{}prohibitionType"/>
 *         &lt;element name="delete" type="{}deleteType"/>
 *         &lt;element name="crossing" type="{}crossingType"/>
 *       &lt;/choice>
 *       &lt;attribute name="version">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="\d+.\d+"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "connectionsType", propOrder = {
    "connectionOrProhibitionOrDelete"
})
public class ConnectionsType {

    @XmlElements({
        @XmlElement(name = "connection", type = ConnectionType.class),
        @XmlElement(name = "prohibition", type = ProhibitionType.class),
        @XmlElement(name = "delete", type = DeleteType.class),
        @XmlElement(name = "crossing", type = CrossingType.class)
    })
    protected List<Object> connectionOrProhibitionOrDelete;
    @XmlAttribute(name = "version")
    protected String version;

    /**
     * Gets the value of the connectionOrProhibitionOrDelete property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the connectionOrProhibitionOrDelete property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConnectionOrProhibitionOrDelete().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConnectionType }
     * {@link ProhibitionType }
     * {@link DeleteType }
     * {@link CrossingType }
     * 
     * 
     */
    public List<Object> getConnectionOrProhibitionOrDelete() {
        if (connectionOrProhibitionOrDelete == null) {
            connectionOrProhibitionOrDelete = new ArrayList<Object>();
        }
        return this.connectionOrProhibitionOrDelete;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
