/**
 * Copyright (c) 2014, Oliver Kleine, Institute of Telematics, University of Luebeck
 * All rights reserved
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the
 * following conditions are met:
 *
 *  - Redistributions of source messageCode must retain the above copyright notice, this list of conditions and the following
 *    disclaimer.
 *
 *  - Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
 *    following disclaimer in the documentation and/or other materials provided with the distribution.
 *
 *  - Neither the name of the University of Luebeck nor the names of its contributors may be used to endorse or promote
 *    products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.16 at 12:03:39 PM CEST 
//


package de.uniluebeck.itm.osm2sumo.elements;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for locationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="locationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="netOffset">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="(\-)?(\d+|(\d*.\d+)),(\-)?(\d+|(\d*.\d+))"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="convBoundary">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="(\-)?(\d+|(\d*.\d+)),(\-)?(\d+|(\d*.\d+)),(\-)?(\d+|(\d*.\d+)),(\-)?(\d+|(\d*.\d+))"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="origBoundary">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="(\-)?(\d+|(\d*.\d+)),(\-)?(\d+|(\d*.\d+)),(\-)?(\d+|(\d*.\d+)),(\-)?(\d+|(\d*.\d+))"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="projParameter" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "locationType")
public class LocationType {

    @XmlAttribute(name = "netOffset")
    protected String netOffset;
    @XmlAttribute(name = "convBoundary")
    protected String convBoundary;
    @XmlAttribute(name = "origBoundary")
    protected String origBoundary;
    @XmlAttribute(name = "projParameter", required = true)
    protected String projParameter;

    /**
     * Gets the value of the netOffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetOffset() {
        return netOffset;
    }

    /**
     * Sets the value of the netOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetOffset(String value) {
        this.netOffset = value;
    }

    /**
     * Gets the value of the convBoundary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConvBoundary() {
        return convBoundary;
    }

    /**
     * Sets the value of the convBoundary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConvBoundary(String value) {
        this.convBoundary = value;
    }

    /**
     * Gets the value of the origBoundary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigBoundary() {
        return origBoundary;
    }

    /**
     * Sets the value of the origBoundary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigBoundary(String value) {
        this.origBoundary = value;
    }

    /**
     * Gets the value of the projParameter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjParameter() {
        return projParameter;
    }

    /**
     * Sets the value of the projParameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjParameter(String value) {
        this.projParameter = value;
    }

}
